# Continuous Integration (CI) is the practice, in software
# engineering, of merging all developer working copies with a shared mainline
# several times a day < https://docs.platformio.org/page/ci/index.html >

language: python
python:
    - "2.7"

sudo: false
cache:
    directories:
        - "~/.platformio"

install:
    - pip install -U platformio
    - platformio update
    - export PLATFORMIO_BUILD_FLAGS="-D TRAVIS_CI"
    # Install the required libraries
    #   https://platformio.org/lib/show/794/xxtea-lib
    #   https://platformio.org/lib/show/126/FastLED
    - platformio lib -g install 126 794

script:
    - platformio run
